from selenium.webdriver.common.by import By
"""
首页底部导航栏
"""
#萌股按钮
layout_stock=(By.ID,'com.hoolai.moego:id/layout_stock')
#社区按钮
layout_community=(By.ID,'com.hoolai.moego:id/layout_community')
#发现按钮
layout_find=(By.ID,'ccom.hoolai.moego:id/layout_find')
#消息按钮
layout_news=(By.ID,'com.hoolai.moego:id/layout_news')
#我按钮
layout_my=(By.ID,'com.hoolai.moego:id/layout_my')

'''
我页面
'''

#登录按钮
login=(By.ID,'com.hoolai.moego:id/login')
#注册按钮
register=(By.ID,'com.hoolai.moego:id/register')
#关注按钮
rlAttention=(By.ID,'com.hoolai.moego:id/rlAttention')
#粉丝按钮
rlFans=(By.ID,'com.hoolai.moego:id/rlFans')
#动态按钮
rlCard=(By.ID,'com.hoolai.moego:id/rlCard')
#banner
vp_banner=(By.ID,'com.hoolai.moego:id/vp_banner')
#萌股会员按钮
vip=(By.ID,'com.hoolai.moego:id/vip')
# 萌股商城按钮
shopping=(By.ID,'com.hoolai.moego:id/shopping')
#真爱标签按钮
label=(By.ID,'com.hoolai.moego:id/label')
#信誉分按钮
credit=(By.ID,'com.hoolai.moego:id/credit')
# 我的收藏按钮
collection=(By.ID,'com.hoolai.moego:id/collection')
#浏览历史按钮
history=(By.ID,'com.hoolai.moego:id/history')
#联系客服按钮
start_customerservice=(By.ID,'com.hoolai.moego:id/start_customerservice')
#设置按钮
more_setup=(By.ID,'com.hoolai.moego:id/more_setup')

'''
登录页面
'''
#左上返回按钮
ly_return=(By.ID,'com.hoolai.moego:id/ly_return')
#输入手机号输入框
et_username=(By.ID,'com.hoolai.moego:id/et_username')
#输入密码输入框
et_password=(By.ID,'com.hoolai.moego:id/et_password')
#登录按钮
btn_login=(By.ID,'com.hoolai.moego:id/btn_login')
#我页面注册按钮
btn_register=(By.ID,'com.hoolai.moego:id/btn_register')
#QQ登录按钮
iv_qq_login=(By.ID,'com.hoolai.moego:id/iv_qq_login')
#微信登录按钮
iv_weixin_login=(By.ID,'com.hoolai.moego:id/iv_weixin_login')
#新浪微博登录按钮
iv_sina_login=(By.ID,'com.hoolai.moego:id/iv_sina_login')
#萌股卸载选择按钮
ckbox_login_icon=(By.ID,'com.hoolai.moego:id/ckbox_login_icon')
#萌股协议可点击文字
txt_login_agree=(By.ID,'com.hoolai.moego:id/txt_login_agree')
#清除手机号按钮
ivCleanphone=(By.ID,'com.hoolai.moego:id/ivCleanphone')
#展示密码按钮
iv_show_pwd=(By.ID,'com.hoolai.moego:id/iv_show_pwd')
'''
注册页面
'''
#左上返回按钮
rl_Back=(By.ID,'com.hoolai.moego:id/rl_Back')
#输入手机号输入框
et_phone_number=(By.ID,'com.hoolai.moego:id/et_phone_number')
#输入验证码输入框
et_verification_code=(By.ID,'com.hoolai.moego:id/et_verification_code')
#输入密码输入框
btn_set_password=(By.ID,'com.hoolai.moego:id/btn_set_password')
#再次输入密码
btn_set_password_confirm=(By.ID,'com.hoolai.moego:id/btn_set_password_confirm')
#注册页注册按钮（同我页面）
# btn_register=(By.ID,'com.hoolai.moego:id/btn_register')
'''
设置页面
'''